# base configurations
dist: xenial
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

# no submodules
git:
  submodules: false

# command to install dependencies
install:
  - rm -f setup.py
  - cp -f scripts/setup.pypi.py setup.py
  - pip install -r requirements-ci.txt

# command to run tests
script:
  - coverage run tests/test.py

# coverage
after_success:
  - codecov
